/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Text;
using Thrift.Protocol;

namespace Hive
{
#if !SILVERLIGHT

    [Serializable]
#endif
    public partial class CommitTxnRequest : TBase
    {
        public long Txnid { get; set; }

        public CommitTxnRequest()
        {
        }

        public CommitTxnRequest(long txnid)
            : this()
        {
            this.Txnid = txnid;
        }

        public void Read(TProtocol iprot)
        {
            bool isset_txnid = false;
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.I64)
                        {
                            Txnid = iprot.ReadI64();
                            isset_txnid = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
            if (!isset_txnid)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
        }

        public void Write(TProtocol oprot)
        {
            TStruct struc = new TStruct("CommitTxnRequest");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            field.Name = "txnid";
            field.Type = TType.I64;
            field.ID = 1;
            oprot.WriteFieldBegin(field);
            oprot.WriteI64(Txnid);
            oprot.WriteFieldEnd();
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder("CommitTxnRequest(");
            sb.Append("Txnid: ");
            sb.Append(Txnid);
            sb.Append(")");
            return sb.ToString();
        }
    }
}