/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Text;
using Thrift.Protocol;

namespace Hive
{
#if !SILVERLIGHT

    [Serializable]
#endif
    public partial class CompactionRequest : TBase
    {
        private string _partitionname;
        private string _runas;

        public string Dbname { get; set; }

        public string Tablename { get; set; }

        public string Partitionname
        {
            get
            {
                return _partitionname;
            }
            set
            {
                __isset.partitionname = true;
                this._partitionname = value;
            }
        }

        /// <summary>
        ///
        /// <seealso cref="CompactionType"/>
        /// </summary>
        public CompactionType Type { get; set; }

        public string Runas
        {
            get
            {
                return _runas;
            }
            set
            {
                __isset.runas = true;
                this._runas = value;
            }
        }

        public Isset __isset;
#if !SILVERLIGHT

        [Serializable]
#endif
        public struct Isset
        {
            public bool partitionname;
            public bool runas;
        }

        public CompactionRequest()
        {
        }

        public CompactionRequest(string dbname, string tablename, CompactionType type)
            : this()
        {
            this.Dbname = dbname;
            this.Tablename = tablename;
            this.Type = type;
        }

        public void Read(TProtocol iprot)
        {
            bool isset_dbname = false;
            bool isset_tablename = false;
            bool isset_type = false;
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.String)
                        {
                            Dbname = iprot.ReadString();
                            isset_dbname = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    case 2:
                        if (field.Type == TType.String)
                        {
                            Tablename = iprot.ReadString();
                            isset_tablename = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    case 3:
                        if (field.Type == TType.String)
                        {
                            Partitionname = iprot.ReadString();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    case 4:
                        if (field.Type == TType.I32)
                        {
                            Type = (CompactionType)iprot.ReadI32();
                            isset_type = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    case 5:
                        if (field.Type == TType.String)
                        {
                            Runas = iprot.ReadString();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
            if (!isset_dbname)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
            if (!isset_tablename)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
            if (!isset_type)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
        }

        public void Write(TProtocol oprot)
        {
            TStruct struc = new TStruct("CompactionRequest");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            field.Name = "dbname";
            field.Type = TType.String;
            field.ID = 1;
            oprot.WriteFieldBegin(field);
            oprot.WriteString(Dbname);
            oprot.WriteFieldEnd();
            field.Name = "tablename";
            field.Type = TType.String;
            field.ID = 2;
            oprot.WriteFieldBegin(field);
            oprot.WriteString(Tablename);
            oprot.WriteFieldEnd();
            if (Partitionname != null && __isset.partitionname)
            {
                field.Name = "partitionname";
                field.Type = TType.String;
                field.ID = 3;
                oprot.WriteFieldBegin(field);
                oprot.WriteString(Partitionname);
                oprot.WriteFieldEnd();
            }
            field.Name = "type";
            field.Type = TType.I32;
            field.ID = 4;
            oprot.WriteFieldBegin(field);
            oprot.WriteI32((int)Type);
            oprot.WriteFieldEnd();
            if (Runas != null && __isset.runas)
            {
                field.Name = "runas";
                field.Type = TType.String;
                field.ID = 5;
                oprot.WriteFieldBegin(field);
                oprot.WriteString(Runas);
                oprot.WriteFieldEnd();
            }
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder("CompactionRequest(");
            sb.Append("Dbname: ");
            sb.Append(Dbname);
            sb.Append(",Tablename: ");
            sb.Append(Tablename);
            sb.Append(",Partitionname: ");
            sb.Append(Partitionname);
            sb.Append(",Type: ");
            sb.Append(Type);
            sb.Append(",Runas: ");
            sb.Append(Runas);
            sb.Append(")");
            return sb.ToString();
        }
    }
}