/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hive
{
    /// <summary>
    /// Common status reporting mechanism across all services
    /// </summary>
    public enum fb_status
    {
        DEAD = 0,
        STARTING = 1,
        ALIVE = 2,
        STOPPING = 3,
        STOPPED = 4,
        WARNING = 5,
    }
}