/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Collections.Generic;
using System.Text;
using Thrift.Protocol;

namespace Hive
{
#if !SILVERLIGHT

    [Serializable]
#endif
    public partial class GetRoleGrantsForPrincipalResponse : TBase
    {
        public List<RolePrincipalGrant> PrincipalGrants { get; set; }

        public GetRoleGrantsForPrincipalResponse()
        {
        }

        public GetRoleGrantsForPrincipalResponse(List<RolePrincipalGrant> principalGrants)
            : this()
        {
            this.PrincipalGrants = principalGrants;
        }

        public void Read(TProtocol iprot)
        {
            bool isset_principalGrants = false;
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.List)
                        {
                            {
                                PrincipalGrants = new List<RolePrincipalGrant>();
                                TList _list39 = iprot.ReadListBegin();
                                for (int _i40 = 0; _i40 < _list39.Count; ++_i40)
                                {
                                    RolePrincipalGrant _elem41 = new RolePrincipalGrant();
                                    _elem41 = new RolePrincipalGrant();
                                    _elem41.Read(iprot);
                                    PrincipalGrants.Add(_elem41);
                                }
                                iprot.ReadListEnd();
                            }
                            isset_principalGrants = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
            if (!isset_principalGrants)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
        }

        public void Write(TProtocol oprot)
        {
            TStruct struc = new TStruct("GetRoleGrantsForPrincipalResponse");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            field.Name = "principalGrants";
            field.Type = TType.List;
            field.ID = 1;
            oprot.WriteFieldBegin(field);
            {
                oprot.WriteListBegin(new TList(TType.Struct, PrincipalGrants.Count));
                foreach (RolePrincipalGrant _iter42 in PrincipalGrants)
                {
                    _iter42.Write(oprot);
                }
                oprot.WriteListEnd();
            }
            oprot.WriteFieldEnd();
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder("GetRoleGrantsForPrincipalResponse(");
            sb.Append("PrincipalGrants: ");
            sb.Append(PrincipalGrants);
            sb.Append(")");
            return sb.ToString();
        }
    }
}