/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Text;
using Thrift.Protocol;

namespace Hive
{
#if !SILVERLIGHT

    [Serializable]
#endif
    public partial class ResourceUri : TBase
    {
        private ResourceType _resourceType;
        private string _uri;

        /// <summary>
        ///
        /// <seealso cref="ResourceType"/>
        /// </summary>
        public ResourceType ResourceType
        {
            get
            {
                return _resourceType;
            }
            set
            {
                __isset.resourceType = true;
                this._resourceType = value;
            }
        }

        public string Uri
        {
            get
            {
                return _uri;
            }
            set
            {
                __isset.uri = true;
                this._uri = value;
            }
        }

        public Isset __isset;
#if !SILVERLIGHT

        [Serializable]
#endif
        public struct Isset
        {
            public bool resourceType;
            public bool uri;
        }

        public ResourceUri()
        {
        }

        public void Read(TProtocol iprot)
        {
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.I32)
                        {
                            ResourceType = (ResourceType)iprot.ReadI32();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    case 2:
                        if (field.Type == TType.String)
                        {
                            Uri = iprot.ReadString();
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
        }

        public void Write(TProtocol oprot)
        {
            TStruct struc = new TStruct("ResourceUri");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            if (__isset.resourceType)
            {
                field.Name = "resourceType";
                field.Type = TType.I32;
                field.ID = 1;
                oprot.WriteFieldBegin(field);
                oprot.WriteI32((int)ResourceType);
                oprot.WriteFieldEnd();
            }
            if (Uri != null && __isset.uri)
            {
                field.Name = "uri";
                field.Type = TType.String;
                field.ID = 2;
                oprot.WriteFieldBegin(field);
                oprot.WriteString(Uri);
                oprot.WriteFieldEnd();
            }
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder("ResourceUri(");
            sb.Append("ResourceType: ");
            sb.Append(ResourceType);
            sb.Append(",Uri: ");
            sb.Append(Uri);
            sb.Append(")");
            return sb.ToString();
        }
    }
}