/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Collections.Generic;
using System.Text;
using Thrift.Protocol;

namespace Hive
{
#if !SILVERLIGHT

    [Serializable]
#endif
    public partial class ShowCompactResponse : TBase
    {
        public List<ShowCompactResponseElement> Compacts { get; set; }

        public ShowCompactResponse()
        {
        }

        public ShowCompactResponse(List<ShowCompactResponseElement> compacts)
            : this()
        {
            this.Compacts = compacts;
        }

        public void Read(TProtocol iprot)
        {
            bool isset_compacts = false;
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.List)
                        {
                            {
                                Compacts = new List<ShowCompactResponseElement>();
                                TList _list225 = iprot.ReadListBegin();
                                for (int _i226 = 0; _i226 < _list225.Count; ++_i226)
                                {
                                    ShowCompactResponseElement _elem227 = new ShowCompactResponseElement();
                                    _elem227 = new ShowCompactResponseElement();
                                    _elem227.Read(iprot);
                                    Compacts.Add(_elem227);
                                }
                                iprot.ReadListEnd();
                            }
                            isset_compacts = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
            if (!isset_compacts)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
        }

        public void Write(TProtocol oprot)
        {
            TStruct struc = new TStruct("ShowCompactResponse");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            field.Name = "compacts";
            field.Type = TType.List;
            field.ID = 1;
            oprot.WriteFieldBegin(field);
            {
                oprot.WriteListBegin(new TList(TType.Struct, Compacts.Count));
                foreach (ShowCompactResponseElement _iter228 in Compacts)
                {
                    _iter228.Write(oprot);
                }
                oprot.WriteListEnd();
            }
            oprot.WriteFieldEnd();
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder("ShowCompactResponse(");
            sb.Append("Compacts: ");
            sb.Append(Compacts);
            sb.Append(")");
            return sb.ToString();
        }
    }
}