/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Collections.Generic;
using System.Text;
using Thrift.Protocol;

namespace Hive
{
#if !SILVERLIGHT

    [Serializable]
#endif
    public partial class TableStatsRequest : TBase
    {
        public string DbName { get; set; }

        public string TblName { get; set; }

        public List<string> ColNames { get; set; }

        public TableStatsRequest()
        {
        }

        public TableStatsRequest(string dbName, string tblName, List<string> colNames)
            : this()
        {
            this.DbName = dbName;
            this.TblName = tblName;
            this.ColNames = colNames;
        }

        public void Read(TProtocol iprot)
        {
            bool isset_dbName = false;
            bool isset_tblName = false;
            bool isset_colNames = false;
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.String)
                        {
                            DbName = iprot.ReadString();
                            isset_dbName = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    case 2:
                        if (field.Type == TType.String)
                        {
                            TblName = iprot.ReadString();
                            isset_tblName = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    case 3:
                        if (field.Type == TType.List)
                        {
                            {
                                ColNames = new List<string>();
                                TList _list161 = iprot.ReadListBegin();
                                for (int _i162 = 0; _i162 < _list161.Count; ++_i162)
                                {
                                    string _elem163 = null;
                                    _elem163 = iprot.ReadString();
                                    ColNames.Add(_elem163);
                                }
                                iprot.ReadListEnd();
                            }
                            isset_colNames = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
            if (!isset_dbName)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
            if (!isset_tblName)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
            if (!isset_colNames)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
        }

        public void Write(TProtocol oprot)
        {
            TStruct struc = new TStruct("TableStatsRequest");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            field.Name = "dbName";
            field.Type = TType.String;
            field.ID = 1;
            oprot.WriteFieldBegin(field);
            oprot.WriteString(DbName);
            oprot.WriteFieldEnd();
            field.Name = "tblName";
            field.Type = TType.String;
            field.ID = 2;
            oprot.WriteFieldBegin(field);
            oprot.WriteString(TblName);
            oprot.WriteFieldEnd();
            field.Name = "colNames";
            field.Type = TType.List;
            field.ID = 3;
            oprot.WriteFieldBegin(field);
            {
                oprot.WriteListBegin(new TList(TType.String, ColNames.Count));
                foreach (string _iter164 in ColNames)
                {
                    oprot.WriteString(_iter164);
                }
                oprot.WriteListEnd();
            }
            oprot.WriteFieldEnd();
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder("TableStatsRequest(");
            sb.Append("DbName: ");
            sb.Append(DbName);
            sb.Append(",TblName: ");
            sb.Append(TblName);
            sb.Append(",ColNames: ");
            sb.Append(ColNames);
            sb.Append(")");
            return sb.ToString();
        }
    }
}