/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Collections.Generic;
using System.Text;
using Thrift.Protocol;

namespace Hive
{
#if !SILVERLIGHT

    [Serializable]
#endif
    public partial class TableStatsResult : TBase
    {
        public List<ColumnStatisticsObj> TableStats { get; set; }

        public TableStatsResult()
        {
        }

        public TableStatsResult(List<ColumnStatisticsObj> tableStats)
            : this()
        {
            this.TableStats = tableStats;
        }

        public void Read(TProtocol iprot)
        {
            bool isset_tableStats = false;
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == TType.List)
                        {
                            {
                                TableStats = new List<ColumnStatisticsObj>();
                                TList _list148 = iprot.ReadListBegin();
                                for (int _i149 = 0; _i149 < _list148.Count; ++_i149)
                                {
                                    ColumnStatisticsObj _elem150 = new ColumnStatisticsObj();
                                    _elem150 = new ColumnStatisticsObj();
                                    _elem150.Read(iprot);
                                    TableStats.Add(_elem150);
                                }
                                iprot.ReadListEnd();
                            }
                            isset_tableStats = true;
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;

                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
            if (!isset_tableStats)
                throw new TProtocolException(TProtocolException.INVALID_DATA);
        }

        public void Write(TProtocol oprot)
        {
            TStruct struc = new TStruct("TableStatsResult");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            field.Name = "tableStats";
            field.Type = TType.List;
            field.ID = 1;
            oprot.WriteFieldBegin(field);
            {
                oprot.WriteListBegin(new TList(TType.Struct, TableStats.Count));
                foreach (ColumnStatisticsObj _iter151 in TableStats)
                {
                    _iter151.Write(oprot);
                }
                oprot.WriteListEnd();
            }
            oprot.WriteFieldEnd();
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder("TableStatsResult(");
            sb.Append("TableStats: ");
            sb.Append(TableStats);
            sb.Append(")");
            return sb.ToString();
        }
    }
}