/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hive
{
    public static class hive_metastoreConstants
    {
        public static string DDL_TIME = "transient_lastDdlTime";
        public static string HIVE_FILTER_FIELD_OWNER = "hive_filter_field_owner__";
        public static string HIVE_FILTER_FIELD_PARAMS = "hive_filter_field_params__";
        public static string HIVE_FILTER_FIELD_LAST_ACCESS = "hive_filter_field_last_access__";
        public static string IS_ARCHIVED = "is_archived";
        public static string ORIGINAL_LOCATION = "original_location";
        public static string IS_IMMUTABLE = "immutable";
        public static string META_TABLE_COLUMNS = "columns";
        public static string META_TABLE_COLUMN_TYPES = "columns.types";
        public static string BUCKET_FIELD_NAME = "bucket_field_name";
        public static string BUCKET_COUNT = "bucket_count";
        public static string FIELD_TO_DIMENSION = "field_to_dimension";
        public static string META_TABLE_NAME = "name";
        public static string META_TABLE_DB = "db";
        public static string META_TABLE_LOCATION = "location";
        public static string META_TABLE_SERDE = "serde";
        public static string META_TABLE_PARTITION_COLUMNS = "partition_columns";
        public static string META_TABLE_PARTITION_COLUMN_TYPES = "partition_columns.types";
        public static string FILE_INPUT_FORMAT = "file.inputformat";
        public static string FILE_OUTPUT_FORMAT = "file.outputformat";
        public static string META_TABLE_STORAGE = "storage_handler";
    }
}