/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hive
{
    public enum HiveObjectType
    {
        GLOBAL = 1,
        DATABASE = 2,
        TABLE = 3,
        PARTITION = 4,
        COLUMN = 5,
    }
}