/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hive
{
    public enum LockState
    {
        ACQUIRED = 1,
        WAITING = 2,
        ABORT = 3,
        NOT_ACQUIRED = 4,
    }
}