/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hive
{
    public enum NodeType
    {
        OPERATOR = 0,
        STAGE = 1,
    }
}