/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hive
{
    public enum PrincipalType
    {
        USER = 1,
        ROLE = 2,
        GROUP = 3,
    }
}