/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hive
{
    public enum StageType
    {
        CONDITIONAL = 0,
        COPY = 1,
        DDL = 2,
        MAPRED = 3,
        EXPLAIN = 4,
        FETCH = 5,
        FUNC = 6,
        MAPREDLOCAL = 7,
        MOVE = 8,
        STATS = 9,
        DEPENDENCY_COLLECTION = 10,
        COLUMNSTATS = 11,
    }
}