/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hive2
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TOpenSessionResp : TBase
  {
    private TSessionHandle _sessionHandle;
    private Dictionary<string, string> _configuration;

    public TStatus Status { get; set; }

    /// <summary>
    /// 
    /// <seealso cref="TProtocolVersion"/>
    /// </summary>
    public TProtocolVersion ServerProtocolVersion { get; set; }

    public TSessionHandle SessionHandle
    {
      get
      {
        return _sessionHandle;
      }
      set
      {
        __isset.sessionHandle = true;
        this._sessionHandle = value;
      }
    }

    public Dictionary<string, string> Configuration
    {
      get
      {
        return _configuration;
      }
      set
      {
        __isset.configuration = true;
        this._configuration = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool sessionHandle;
      public bool configuration;
    }

    public TOpenSessionResp() {
      this.ServerProtocolVersion = TProtocolVersion.HIVE_CLI_SERVICE_PROTOCOL_V6;
    }

    public TOpenSessionResp(TStatus status, TProtocolVersion serverProtocolVersion) : this() {
      this.Status = status;
      this.ServerProtocolVersion = serverProtocolVersion;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_status = false;
      bool isset_serverProtocolVersion = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Status = new TStatus();
              Status.Read(iprot);
              isset_status = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              ServerProtocolVersion = (TProtocolVersion)iprot.ReadI32();
              isset_serverProtocolVersion = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              SessionHandle = new TSessionHandle();
              SessionHandle.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Map) {
              {
                Configuration = new Dictionary<string, string>();
                TMap _map76 = iprot.ReadMapBegin();
                for( int _i77 = 0; _i77 < _map76.Count; ++_i77)
                {
                  string _key78;
                  string _val79;
                  _key78 = iprot.ReadString();
                  _val79 = iprot.ReadString();
                  Configuration[_key78] = _val79;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_status)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_serverProtocolVersion)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TOpenSessionResp");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "status";
      field.Type = TType.Struct;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      Status.Write(oprot);
      oprot.WriteFieldEnd();
      field.Name = "serverProtocolVersion";
      field.Type = TType.I32;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32((int)ServerProtocolVersion);
      oprot.WriteFieldEnd();
      if (SessionHandle != null && __isset.sessionHandle) {
        field.Name = "sessionHandle";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        SessionHandle.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Configuration != null && __isset.configuration) {
        field.Name = "configuration";
        field.Type = TType.Map;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.String, Configuration.Count));
          foreach (string _iter80 in Configuration.Keys)
          {
            oprot.WriteString(_iter80);
            oprot.WriteString(Configuration[_iter80]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TOpenSessionResp(");
      sb.Append("Status: ");
      sb.Append(Status== null ? "<null>" : Status.ToString());
      sb.Append(",ServerProtocolVersion: ");
      sb.Append(ServerProtocolVersion);
      sb.Append(",SessionHandle: ");
      sb.Append(SessionHandle== null ? "<null>" : SessionHandle.ToString());
      sb.Append(",Configuration: ");
      sb.Append(Configuration);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
