/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Hive2
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TOperationHandle : TBase
  {
    private double _modifiedRowCount;

    public THandleIdentifier OperationId { get; set; }

    /// <summary>
    /// 
    /// <seealso cref="TOperationType"/>
    /// </summary>
    public TOperationType OperationType { get; set; }

    public bool HasResultSet { get; set; }

    public double ModifiedRowCount
    {
      get
      {
        return _modifiedRowCount;
      }
      set
      {
        __isset.modifiedRowCount = true;
        this._modifiedRowCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool modifiedRowCount;
    }

    public TOperationHandle() {
    }

    public TOperationHandle(THandleIdentifier operationId, TOperationType operationType, bool hasResultSet) : this() {
      this.OperationId = operationId;
      this.OperationType = operationType;
      this.HasResultSet = hasResultSet;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_operationId = false;
      bool isset_operationType = false;
      bool isset_hasResultSet = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              OperationId = new THandleIdentifier();
              OperationId.Read(iprot);
              isset_operationId = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              OperationType = (TOperationType)iprot.ReadI32();
              isset_operationType = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Bool) {
              HasResultSet = iprot.ReadBool();
              isset_hasResultSet = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Double) {
              ModifiedRowCount = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_operationId)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_operationType)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_hasResultSet)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TOperationHandle");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "operationId";
      field.Type = TType.Struct;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      OperationId.Write(oprot);
      oprot.WriteFieldEnd();
      field.Name = "operationType";
      field.Type = TType.I32;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32((int)OperationType);
      oprot.WriteFieldEnd();
      field.Name = "hasResultSet";
      field.Type = TType.Bool;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteBool(HasResultSet);
      oprot.WriteFieldEnd();
      if (__isset.modifiedRowCount) {
        field.Name = "modifiedRowCount";
        field.Type = TType.Double;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(ModifiedRowCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TOperationHandle(");
      sb.Append("OperationId: ");
      sb.Append(OperationId== null ? "<null>" : OperationId.ToString());
      sb.Append(",OperationType: ");
      sb.Append(OperationType);
      sb.Append(",HasResultSet: ");
      sb.Append(HasResultSet);
      sb.Append(",ModifiedRowCount: ");
      sb.Append(ModifiedRowCount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
